name        : python-pyliblzma
version     : 0.5.3
release     : 2
source      :
    - http://pypi.python.org/packages/source/p/pyliblzma/pyliblzma-0.5.3.tar.bz2 : 08d762f36d5e59fb9bb0e22e000c300b21f97e35b713321ee504cfb442667957
license     :
    - MIT
summary     : Python bindings for lzma
builddeps   :
    - pkgconfig(liblzma)
    - pkgconfig(python-2.7)
    - python-setuptools
description : |
    pyliblzma provides a python interface for the liblzma library to read/write data that has been compressed/decompressed with lzma utils.
install:
    python setup.py install --root="$installdir" --no-compile -O0
